# Generated by Django 4.1.5 on 2023-01-06 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField()),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Taste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('count_in_stock', models.IntegerField()),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Elfbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('description', models.TextField()),
                ('nicotine', models.CharField(max_length=20)),
                ('battery', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('charge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='elfbar_api.charge')),
                ('taste', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='elfbar_api.taste')),
            ],
        ),
    ]
