# Generated by Django 4.1.5 on 2023-01-06 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elfbar_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elfbar',
            name='battery',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='elfbar',
            name='brand',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='elfbar',
            name='image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='elfbar',
            name='nicotine',
            field=models.CharField(max_length=100),
        ),
    ]
