# Generated by Django 4.1 on 2023-03-08 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elfbar_api', '0002_alter_elfbar_battery_alter_elfbar_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elfbar',
            name='charge',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Charge',
        ),
    ]
