# Generated by Django 4.1 on 2023-03-22 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elfbar_api', '0003_alter_elfbar_charge_delete_charge'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('elfbar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='elfbar_api.elfbar')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('postal_code', models.IntegerField()),
                ('order_item', models.ManyToManyField(to='elfbar_api.orderitem')),
            ],
        ),
    ]
