# Generated by Django 4.1 on 2023-03-22 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elfbar_api', '0004_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='price',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='elfbar',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
