# Generated by Django 4.1 on 2023-03-23 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elfbar_api', '0005_orderitem_price_alter_orderitem_elfbar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_item',
        ),
        migrations.AddField(
            model_name='order',
            name='order_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='elfbar_api.orderitem'),
        ),
    ]
