# Generated by Django 4.1 on 2023-03-26 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elfbar_api', '0012_alter_orderitem_elfbar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='elfbar',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
